



//////////////////////////////////////////
//EXAMINEE
//--------------------------------------------------------------
//-------------------新增三个自动程序------------------
//--------------------------------------------------------------

//  press   "滚动"  ------------------->knead  knock  都停 walk动
//  wavlet "  揉捶, 韵律"  ---------->knead 动 knock  walk动
//  RUBBING" 搓背"  ---------->knead -rubbing   knock stop
//  SOFT_KNOCK " "      ----------> knead 停 knock  run stop
//  
//--------------------------------------------------------------------------
//  subFun,    walkMotorLoc,  walkParam,  KneadState , KneadCycle ,  KnockState , KnockRunTime  ,KnockStopTime, KnockSpeed
//  EXAMINE
//  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER     ,0,KNEAD_STOP        ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKER,   _3D_SPEED_4,0},

const WALK_KNEAD_KNOCK_MOTOR_STRUCT_AUTO AutoFunction6[] = 
{


  // address:0
  // 第一分钟
  //定点到WAIST
  //敲打(WAIST-HIP)  10S // SZ = 18
  // 0:
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION,KNEAD_STOP_AT_MAX,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},    
  // 1
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION,KNEAD_STOP_AT_MAX,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  // 2
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},    
  // 3
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION,KNEAD_STOP_AT_MED,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  // 4
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},    
  // 5
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION,KNEAD_STOP_AT_MIN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  // 6
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},    
   // 7 
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_STOP_AT_MAX,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  // 8
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},    
  // 9
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,WAIST_POSITION+PARTIAL_DIFF,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  // 10
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  // 11
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,WAIST_POSITION+PARTIAL_DIFF,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  // 12
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  // 13
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,WAIST_POSITION+PARTIAL_DIFF,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  // 14
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  // 15
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION+PARTIAL_DIFF,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  // 16
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  // 17
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION+PARTIAL_DIFF,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  // 
  //-------------------------------------------------------------------------------------------------------  
  // address : 18
  // 第二分钟   
  //扣击 (WAIST-HIP)  60S  SZ = 22
  // 1
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION-PARTIAL_DIFF,KNEAD_STOP_AT_MIN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  // 2
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},    
  // 3
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_STOP_AT_MIN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},    
  // 4
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},      
  // 5
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION+PARTIAL_DIFF,KNEAD_STOP_AT_MIN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},    
  // 6
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},      


  // 1
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION-PARTIAL_DIFF,KNEAD_STOP_AT_MAX,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  // 2
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},    
  // 3
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_STOP_AT_MAX,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},    
  // 4
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},      
  // 5
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION+PARTIAL_DIFF,KNEAD_STOP_AT_MAX,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},    
  // 6
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},      



  // 1
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION-PARTIAL_DIFF,KNEAD_STOP_AT_MED,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  // 2
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},    
  // 3
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_STOP_AT_MED,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},    
  // 4
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},      
  // 5
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION+PARTIAL_DIFF,KNEAD_STOP_AT_MED,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},    
  // 6
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},      

  // 1
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION-PARTIAL_DIFF,KNEAD_STOP_AT_MIN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  // 2
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},    
  // 3
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_STOP_AT_MIN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},    
  // 4
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},      

  
  //-------------------------------------------------------------------------------------------------------

  // address : 18+22 = 40  
  // 第三分钟  第四分钟  
  //敲击 (WAIST-HIP)  60S
  // 腰部-->背部SZ =  24
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_STOP,4,4,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0}, 
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP,0,KNOCK_RUN_STOP,4,4,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},

  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_STOP_AT_MED,0,KNOCK_RUN_STOP,4,4,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0}, 
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP,0,KNOCK_RUN_STOP,4,4,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},

  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_STOP,4,4,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0}, 
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP,0,KNOCK_RUN_STOP,4,4,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},

  // 背部
  // 27  
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION+2*PARTIAL_DIFF,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_STOP,4,4,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0}, 
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP,0,KNOCK_RUN_STOP,4,4,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},

  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION+2*PARTIAL_DIFF,KNEAD_STOP_AT_MED,0,KNOCK_RUN_STOP,4,4,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0}, 
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP,0,KNOCK_RUN_STOP,4,4,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},

  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION+2*PARTIAL_DIFF,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_STOP,4,4,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0}, 
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP,0,KNOCK_RUN_STOP,4,4,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //--60S
  // 背部-->臀部
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION+1*PARTIAL_DIFF,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_STOP,4,4,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},   
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,60,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_STOP,4,4,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},     

  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_STOP,4,4,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},   
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,60,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_STOP,4,4,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},     

  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_STOP,4,4,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},   
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,60,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_STOP,4,4,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},     
  //
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_STOP,4,4,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},   
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,60,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_STOP,4,4,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},     
  //
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION,KNEAD_STOP_AT_MED,0,KNOCK_RUN_STOP,4,4,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},   
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,60,KNEAD_STOP_AT_MED,0,KNOCK_RUN_STOP,4,4,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},     
   //
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION+PARTIAL_DIFF,KNEAD_STOP_AT_MED,0,KNOCK_RUN_STOP,4,4,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},   
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,60,KNEAD_STOP_AT_MED,0,KNOCK_RUN_STOP,4,4,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},     
  //--60S   
  // address : 40 +  24 = 64
  // 第五分钟
  // 揉动  
  // 臀部-->肩部 SZ = 18
  // 
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},    
  //
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  //
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},    
  //
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_NeckMed,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  //
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},        
  //  往复2次
  //
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_NeckMed,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_UNDER_SHOULDER,PARTIAL_DIFF,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  //
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_NeckMed,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_UNDER_SHOULDER,PARTIAL_DIFF,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  //
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_NeckMed,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  //
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},        
  // 
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},    
  //
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,50,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  //
  // address : 64 + 18  = 82
  // 第六分钟
  // 揉动  
  // 臀部-->肩部SZ = 18
  // 0
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  // 1
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  //  2 
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  // 3
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  // 4
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  // 5
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},    
   // 6
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_NeckMed,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  // 7
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},         
  //  往复2次
  // 8
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_NeckMed,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  // 9
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_UNDER_SHOULDER,PARTIAL_DIFF,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  // 10
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_NeckMed,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  // 11
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_UNDER_SHOULDER,PARTIAL_DIFF,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  // 揉臀->肩部
  // 12
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  // 13
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},    
  // 14
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  // 15
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  // 16
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  // 17
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  


  // address : 82  + 18 = 100
  // 第七分钟
  //敲打 (SHOULDER-HIP)  60S   SZ = 18
  // 0 
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_SHOULDER,WAIST_POSITION,KNEAD_STOP_AT_MAX,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  // 1
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},      
  // 2
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_STOP_AT_MAX,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},    
  //   3
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},    
  //   4
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION,KNEAD_STOP_AT_MAX,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},    
  //   5
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},    
   // 6
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //  7 
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  // 8
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //  9
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  //  10
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //   11
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},      
  // 12
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_NeckMed,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //  13 
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},      
  //  往复2次
  // 14
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_UNDER_SHOULDER,PARTIAL_DIFF,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  // 15 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_NeckMed,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  // 16
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_UNDER_SHOULDER,PARTIAL_DIFF,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  // 17
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_NeckMed,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //
  // address : 100+ 18 = 118
  // 第8 分钟SZ = 12
  // 揉
  // 0
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  // 1
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  // 2
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  // 3
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  // 4  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  // 5
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},      
  //  往复2次
  // 6
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  // 7
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  // 8
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  // 9
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  // 10
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  // 11
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},   
  // address : 118+12 = 130  
  // 第9 ,10 分钟
  // 揉 SZ = 28

  //--------------------揉敲---------------------------------------
  // 0
    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
    {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,40,KNEAD_STOP_AT_MED,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  
    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
    {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,40,KNEAD_STOP_AT_MED,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  
    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
    {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,40,KNEAD_STOP_AT_MED,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},

    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
    {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,40,KNEAD_STOP_AT_MED,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},

    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,WAIST_POSITION+PARTIAL_DIFF,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
    {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,40,KNEAD_STOP_AT_MED,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},

    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_UNDER_SHOULDER,PARTIAL_DIFF,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
    {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP_AT_MED,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},

    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
    {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP_AT_MED,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},

    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_NeckMed,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
    {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,40,KNEAD_STOP_AT_MED,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
    
    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
    {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,40,KNEAD_STOP_AT_MED,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},

    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_NeckMed,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
    {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,40,KNEAD_STOP_AT_MED,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},


  // address : 130+28 = 158
  //  第 11分钟
  //  往复3次 SZ = 11
  // 0
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_NeckMed,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  // 1
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_UNDER_SHOULDER,PARTIAL_DIFF,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  // 2
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_NeckMed,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  // 3
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_UNDER_SHOULDER,PARTIAL_DIFF,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  // 4
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_NeckMed,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  // 5
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  // 6
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,WAIST_POSITION+PARTIAL_DIFF,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  // 7
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  // 8
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,WAIST_POSITION+PARTIAL_DIFF,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  // 9
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  // 10
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,WAIST_POSITION+PARTIAL_DIFF,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  // address 158 +11 = 169
  // 第 12 ,13 分
  // 腰部-->背部
  // 敲打(WAIST-HIP)  60S SZ = 24
  // 0
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION-PARTIAL_DIFF,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},    
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3},    
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION+PARTIAL_DIFF,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},    
  // 6
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION-PARTIAL_DIFF,KNEAD_STOP_AT_MED,0,KNOCK_RUN_WIDTH,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},    
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_STOP_AT_MED,0,KNOCK_RUN_WIDTH,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},    
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION+PARTIAL_DIFF,KNEAD_STOP_AT_MED,0,KNOCK_RUN_WIDTH,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},    
  // 12
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_UNDER_SHOULDER,PARTIAL_DIFF,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},    
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_UNDER_SHOULDER,PARTIAL_DIFF,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},    
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_UNDER_SHOULDER,PARTIAL_DIFF,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},    
  // 18
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_UNDER_SHOULDER,PARTIAL_DIFF,KNEAD_STOP_AT_MED,0,KNOCK_RUN_WIDTH,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},    
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_UNDER_SHOULDER,PARTIAL_DIFF,KNEAD_STOP_AT_MED,0,KNOCK_RUN_WIDTH,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},    
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_UNDER_SHOULDER,PARTIAL_DIFF,KNEAD_STOP_AT_MED,0,KNOCK_RUN_WIDTH,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},    
  // 
    // address 169+24 = 193
  // 第 14 ,15 分钟扣击
  // 腰部-->背部 SZ = 18;
  // 0
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION-PARTIAL_DIFF,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_STOP,30,20,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  // 1
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION+PARTIAL_DIFF,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_STOP,30,20,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  // 2
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION-PARTIAL_DIFF,KNEAD_STOP_AT_MED,0,KNOCK_RUN_STOP,30,20,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  // 3
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION+PARTIAL_DIFF,KNEAD_STOP_AT_MED,0,KNOCK_RUN_STOP,30,20,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  // 4
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION-PARTIAL_DIFF,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_STOP,30,20,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  // 5
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION+PARTIAL_DIFF,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_STOP,30,20,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  // 6
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION-PARTIAL_DIFF,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_STOP,30,20,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  // 7
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION+PARTIAL_DIFF,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_STOP,30,20,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  // 8
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION-PARTIAL_DIFF,KNEAD_STOP_AT_MED,0,KNOCK_RUN_STOP,30,20,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  // 9
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION+PARTIAL_DIFF,KNEAD_STOP_AT_MED,0,KNOCK_RUN_STOP,30,20,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  // 10
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION-PARTIAL_DIFF,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_STOP,40,20,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  // 11
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION+PARTIAL_DIFF,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_STOP,40,20,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  // 12
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION-PARTIAL_DIFF,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_STOP,40,20,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  // 13
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION+PARTIAL_DIFF,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_STOP,40,20,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  // 14
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION-PARTIAL_DIFF,KNEAD_STOP_AT_MED,0,KNOCK_RUN_STOP,40,20,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  // 15
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION+PARTIAL_DIFF,KNEAD_STOP_AT_MED,0,KNOCK_RUN_STOP,40,20,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  // 16
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION-PARTIAL_DIFF,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_STOP,40,20,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  // 17
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION+PARTIAL_DIFF,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_STOP,40,20,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  
  // address 193 +18 = 211
  // 第 16 分指压SZ = 11
  // 0
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  // 1
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  // 2
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  // 3
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  // 4
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_NeckMed,0,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_STOP,40,20,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  // 5
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_STOP,4,2,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  // 6
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_STOP,4,2,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  // 7
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MED,0,KNOCK_RUN_STOP,4,2,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  // 8
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_STOP,4,2,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  // 9
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MED,0,KNOCK_RUN_STOP,4,2,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  // 10


  
  // 10

  // address 211 +11 = 222 
  // 第 17 分指压SZ = 10

  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_PressNeck,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  
  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_PressNeck,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  
  
  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_SHOULDER,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_PressNeck,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  
  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_NeckMed,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},    
  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_NeckMed,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},

   // address 222+10 = 232
   // 第18  19
   // 0
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,50,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0}, 
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,50,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,WAIST_POSITION+PARTIAL_DIFF,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,50,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_UNDER_SHOULDER,PARTIAL_DIFF,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,50,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,50,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_NeckMed,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,50,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  
   // 6
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,10,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},   
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,10,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},   
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION+PARTIAL_DIFF,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},


   // 0
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_NeckMed,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,50,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},

  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,50,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  

  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_UNDER_SHOULDER,PARTIAL_DIFF,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,50,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  

  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,WAIST_POSITION+PARTIAL_DIFF,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,50,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  

  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,50,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},

  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,50,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0}, 


  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_STOP,4,4,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0}, 
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP,0,KNOCK_RUN_STOP,4,4,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},

  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_STOP,4,4,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0}, 
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP,0,KNOCK_RUN_STOP,4,4,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},


  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,50,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0}, 
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,50,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,50,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_NeckMed,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,50,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},


  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_SHOULDER,0,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_STOP,4,4,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0}, 
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP,0,KNOCK_RUN_STOP,4,4,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},


  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_STOP,4,4,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0}, 
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP,0,KNOCK_RUN_STOP,4,4,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},

  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_STOP,4,4,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0}, 
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP,0,KNOCK_RUN_STOP,4,4,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},

  {BACK_SUB_MODE_PRESS,WALK_LOCATE_NeckMed,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,4,4,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0}, 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,4,4,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0}, 
  
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_NeckMed,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,4,4,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0}, 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,4,4,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0}, 




};

