




// HIP -UP
const WALK_KNEAD_KNOCK_MOTOR_STRUCT_AUTO AutoFunction7[] = 
{	

  // ADDRESS = 1
  // 第一分钟
  // 揉臀部
  // SZ = 11	
  // 0
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  // 1
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  // 2
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,50,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  //  指压臀部.
  // 7
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  // 8
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
   // 9
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
   // 10
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
   //
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},   
    // 4
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,50,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  // 5
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  // 6
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,80,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},    
  //
  //--------------------------------------------------------------------------------------	


  // ADDRESS = 11  
  // 第二分钟  // 第三分钟
  //SZ = 28
  // 0
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION+PARTIAL_DIFF,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},      
  // 2  降
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},      
   // 4 升
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},      
  //  6 升
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION+PARTIAL_DIFF,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},      
  //  8 降
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},      
  //  10 降
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},      
   //  12 升
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},      
  //   14 升
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION+PARTIAL_DIFF,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},    
   //  16 降
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},      
  //   18 降
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},      
   //  20 升
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},      
  //   22 升
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION+PARTIAL_DIFF,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},    
   //  24 降
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},      
  //   26 降
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,60,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},      



  // ADDRESS = 11+28 = 39
  // 第四分钟
  // 揉臀部
  // 指压臀部.
  // SZ = 10
  // 0
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION+PARTIAL_DIFF,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  // 2
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  // 3
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION+PARTIAL_DIFF,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //--------------------------------------------------------------------------------------	
  // 4
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},       
  // 6
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},       
  // 8
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION+PARTIAL_DIFF,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,50,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},       
  //

  // ADDRESS = 39+ 10 = 49
  // 第五分钟第六
  //  指压臀部.
  // SZ= 12
  // 0
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  // 1
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION+PARTIAL_DIFF,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  // 2
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  // 3
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION+PARTIAL_DIFF,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  // 4
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  // 5
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION+PARTIAL_DIFF,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  // 6
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  // 7
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION+PARTIAL_DIFF,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  // 8
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  // 9
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  // 10
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  // 11
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},

  // ADDRESS = 49 + 12 = 61
  // 第七第八第九
  // SZ = 24
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION+PARTIAL_DIFF,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
   // 0
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
   // 1
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION+PARTIAL_DIFF,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
   // 2
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  //  3
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  // 4
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,80,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0}, 


  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION+PARTIAL_DIFF,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
   // 0
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
   // 1
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION+PARTIAL_DIFF,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
   // 2
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  //  3
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  // 4
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,80,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0}, 

  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION+PARTIAL_DIFF,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
   // 0
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
   // 1
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION+PARTIAL_DIFF,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
   // 2
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  //  3
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  // 4
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0}, 


  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION+PARTIAL_DIFF,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
   // 0
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
   // 1
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION+PARTIAL_DIFF,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
   // 2
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  //  3
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //  4
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0}, 



  // ADDRESS = 61 + 24 = 85
   // 第十,十一,十二分钟
  // 揉臀部
  //  指压臀部.
  // SZ = 28
  // 0
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  // 1
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION+PARTIAL_DIFF,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  // 2
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  // 3
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION+PARTIAL_DIFF,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //--------------------------------------------------------------------------------------	
  // 4
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},   
  // 6
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0}, 
  // 8
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION+PARTIAL_DIFF,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0}, 


  // 0
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  // 1
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION+PARTIAL_DIFF,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  // 2
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  // 3
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION+PARTIAL_DIFF,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //--------------------------------------------------------------------------------------	
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_STOP,4,4,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0}, 
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN_STOP,4,4,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},

  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_STOP,4,4,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0}, 
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,40,KNEAD_STOP,0,KNOCK_RUN_STOP,4,4,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},

  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_STOP,4,4,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0}, 
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,40,KNEAD_STOP,0,KNOCK_RUN_STOP,4,4,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //
  

  // 9
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_NeckMed,WAIST_POSITION+PARTIAL_DIFF,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  // 10
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  // 9
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_NeckMed,WAIST_POSITION+PARTIAL_DIFF,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  // 10
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  // 9
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_NeckMed,WAIST_POSITION+PARTIAL_DIFF,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  // 10
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_NeckMed,WAIST_POSITION+PARTIAL_DIFF,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  // 10
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},


  // ADDRESS = 85 + 28 = 113 
  // 第十三
  // 揉动 脖子---> 臀部,扣击臀部.

  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_NeckMed,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0}, 

  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0}, 

  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0}, 
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},   

  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_STOP,4,4,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0}, 
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP,0,KNOCK_RUN_STOP,4,4,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},

  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_STOP,4,4,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0}, 
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP,0,KNOCK_RUN_STOP,4,4,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},

  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_STOP,4,4,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0}, 
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP,0,KNOCK_RUN_STOP,4,4,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},


  // 第十四                                                           更改了+   -  原来是比较单一。
  //
  // 120
  // 0
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION+PARTIAL_DIFF,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  


  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  


  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION+PARTIAL_DIFF,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  


  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION+PARTIAL_DIFF,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  


  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  


  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION+PARTIAL_DIFF,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  //


  // 0
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  


  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION+PARTIAL_DIFF,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  


  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  


  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION+PARTIAL_DIFF,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  


  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  


  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION+PARTIAL_DIFF,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  //

  // 0
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  


  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION+PARTIAL_DIFF,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  


  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  


  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION+PARTIAL_DIFF,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  


  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  


  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION+PARTIAL_DIFF,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  //

  // 0
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  


  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION+PARTIAL_DIFF,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  


  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  


  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION+PARTIAL_DIFF,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  


  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  


  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION+PARTIAL_DIFF,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  //

  // 0
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  


  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION+PARTIAL_DIFF,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  


  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  


  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION+PARTIAL_DIFF,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  


  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  


  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION+PARTIAL_DIFF,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  //

  // 0
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  


  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION+PARTIAL_DIFF,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  


  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  


  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION+PARTIAL_DIFF,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  


  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  


  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION+PARTIAL_DIFF,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  //

  // 0
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  


  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION+PARTIAL_DIFF,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  


  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  


  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION+PARTIAL_DIFF,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  


  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION-PARTIAL_DIFF,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  


  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION+PARTIAL_DIFF,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
  //

  	
};

