//中医理疗  心理SAP
const WALK_KNEAD_KNOCK_MOTOR_STRUCT_AUTO AutoFunction4[] = 
{	
  { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PressNeck, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_5, _3D_PROGRAM, AXIS_STRONGEST, 0, 0 },
  { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_RUN_STOP, 5, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_FITFUL, 5, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_KNEAD, WALK_LOCATE_Ear, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_RUN_STOP, 5, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_KNEAD, WALK_LOCATE_SHOULDER, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_RUN_STOP, 5, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_FITFUL, 3, KNOCK_STOP, 0, 0, SPEED_2, _3D_PROGRAM, AXIS_MIDDLE, _3D_SPEED_2, 0 },
  { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_STOP_AT_MIN, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PROGRAM, AXIS_STRONGEST, _3D_SPEED_2, 0 },
  { BACK_SUB_MODE_PRESS, WALK_LOCATE_NeckMed, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_RUN_STOP, 6, KNOCK_STOP, 0, 0, SPEED_2, _3D_PROGRAM, AXIS_STRONGER, _3D_SPEED_2, 0 },
  { BACK_SUB_MODE_KNEAD, WALK_LOCATE_SHOULDER, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PROGRAM, AXIS_STRONGEST, _3D_SPEED_2, 0 },
  { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_FITFUL, 6, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_PRESS, WALK_DEC_PULSE, 10, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, 0, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_WAVELET, WALK_LOCATE_PARK, 0, KNEAD_RUBBING, 3, KNOCK_PWM, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_STOP_AT_MIN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PROGRAM, AXIS_STRONGER, _3D_SPEED_2, 0 },
  { BACK_SUB_MODE_PRESS, WALK_SHOULDER_WAIST_1_10, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_PRESS, WALK_LOCATE_PARK, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PROGRAM, AXIS_STRONGEST, _3D_SPEED_2, 5 },
  { BACK_SUB_MODE_PRESS, WALK_LOCATE_SHOULDER, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_PRESS, WALK_LOCATE_PARK, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PROGRAM, AXIS_STRONGER, _3D_SPEED_2, 0 },

  { BACK_SUB_MODE_PRESS, WALK_SHOULDER_WAIST_1_10, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
       
  //{ BACK_SUB_MODE_PRESS, WALK_LOCATE_ABSULATE, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PROGRAM, AXIS_STRONGEST, _3D_SPEED_2, 5 },
  { BACK_SUB_MODE_PRESS, WALK_LOCATE_NeckMed, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_PRESS, WALK_LOCATE_PARK, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PROGRAM, AXIS_STRONGER, _3D_SPEED_2, 0 },
   //=========================================肩颈部揉捏-手法1-指压=========================================--22
  { BACK_SUB_MODE_PRESS, WALK_SHOULDER_WAIST_1_10, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_PRESS, WALK_SHOULDER_WAIST_3_10, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PROGRAM, AXIS_STRONGEST, _3D_SPEED_2, 0 },
  
  { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_RUN_STOP, 2, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_WAVELET, WALK_LOCATE_PARK, 0, KNEAD_RUBBING, 2, KNOCK_PWM, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_KNEAD, WALK_SHOULDER_WAIST_5_10, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PROGRAM, AXIS_STRONGER, _3D_SPEED_2, 0 },
  { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_RUN_STOP, 2, KNOCK_STOP, 0, 0, SPEED_2, _3D_PROGRAM, AXIS_STRONGEST, _3D_SPEED_3, 0 },
  { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_STOP_AT_MIN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PROGRAM, AXIS_STRONGER, _3D_SPEED_2, 0 },
   //=========================================背上部指压-揉捏-手法3=========================================--29
  { BACK_SUB_MODE_PRESS, WALK_LOCATE_WAIST, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_STOP_AT_MAX, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PROGRAM, AXIS_STRONGEST, _3D_SPEED_2, 0 },
  { BACK_SUB_MODE_PRESS, WALK_SHOULDER_WAIST_5_10, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_STOP_AT_MIN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_PRESS, WALK_SHOULDER_WAIST_7_10, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 5 },
  { BACK_SUB_MODE_PRESS, WALK_LOCATE_WAIST, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 5 },
  { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_STOP_AT_MAX, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PROGRAM, AXIS_MIDDLE, _3D_SPEED_2, 0 },
  { BACK_SUB_MODE_PRESS, WALK_SHOULDER_WAIST_5_10, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_FITFUL, 3, KNOCK_STOP, 0, 0, SPEED_1, _3D_PROGRAM, AXIS_STRONGEST, _3D_SPEED_3, 0 },
  { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_STOP_AT_MAX, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PROGRAM, AXIS_STRONGER, _3D_SPEED_2, 0 },
   //========================================背下-腰部部指压-揉捏-手法1=========================================--39
  { BACK_SUB_MODE_PRESS, WALK_LOCATE_SHOULDER, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_STOP_AT_MED, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PROGRAM, AXIS_STRONGEST, _3D_SPEED_3, 0 },

  { BACK_SUB_MODE_PRESS, WALK_SHOULDER_WAIST_5_10, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_TOGGLE, 3, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
     //=========================================背上部-指压-手法2=========================================--43
  { BACK_SUB_MODE_KNEAD, WALK_SHOULDER_WAIST_8_10, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_TOGGLE, 5, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_KNEAD, WALK_LOCATE_WAIST, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_TOGGLE, 3, KNOCK_STOP, 0, 0, SPEED_3, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_KNEAD, WALK_LOCATE_ABSULATE, 60, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PROGRAM, AXIS_STRONGER, _3D_SPEED_2, 0 },
  { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_TOGGLE, 3, KNOCK_STOP, 0, 0, SPEED_2, _3D_PROGRAM, AXIS_STRONGEST, _3D_SPEED_2, 0 },
  { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_STOP_AT_MIN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PROGRAM, AXIS_MIDDLE, _3D_SPEED_3, 0 },
  { BACK_SUB_MODE_PRESS, WALK_LOCATE_WAIST, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_PRESS, WALK_SHOULDER_WAIST_8_10, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 5 },
  { BACK_SUB_MODE_PRESS, WALK_SHOULDER_WAIST_9_10, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 4 },
  { BACK_SUB_MODE_PRESS, WALK_LOCATE_WAIST, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PROGRAM, AXIS_STRONGEST, _3D_SPEED_4, 0 },
  { BACK_SUB_MODE_KNEAD, WALK_SHOULDER_WAIST_8_10, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_KNEAD, WALK_LOCATE_ABSULATE, 60, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_KNEAD, WALK_LOCATE_WAIST, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_STOP_AT_MIN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PROGRAM, AXIS_WEAKER, _3D_SPEED_2, 0 },
  { BACK_SUB_MODE_PRESS, WALK_LOCATE_ABSULATE, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_TOGGLE, 6, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_KNEAD, WALK_LOCATE_ABSULATE, 40, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PROGRAM, AXIS_MIDDLE, _3D_SPEED_3, 0 },
  { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_TOGGLE, 2, KNOCK_STOP, 0, 0, SPEED_1, _3D_PROGRAM, AXIS_STRONGEST, _3D_SPEED_3, 0 },
  { BACK_SUB_MODE_KNEAD, WALK_LOCATE_ABSULATE, 60, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_TOGGLE, 2, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_KNEAD, WALK_LOCATE_ABSULATE, 100, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_TOGGLE, 2, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_KNEAD, WALK_LOCATE_WAIST, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_TOGGLE, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_KNEAD, WALK_LOCATE_ABSULATE, 100, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_TOGGLE, 2, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_KNEAD, WALK_LOCATE_ABSULATE, 60, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_TOGGLE, 2, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_KNEAD, WALK_LOCATE_ABSULATE, 40, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_TOGGLE, 2, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_KNEAD, WALK_LOCATE_ABSULATE, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_TOGGLE, 6, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_KNEAD, WALK_LOCATE_ABSULATE, 60, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 5 },
     //=========================================背下部-腰部-臀部-揉捏-手法2=========================================--77
  { BACK_SUB_MODE_KNEAD, WALK_LOCATE_SHOULDER, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_FITFUL, 3, KNOCK_STOP, 0, 0, SPEED_2, _3D_PROGRAM, AXIS_MIDDLE, _3D_SPEED_2, 0 },
  { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_STOP_AT_MIN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PROGRAM, AXIS_STRONGEST, _3D_SPEED_2, 5 },
  { BACK_SUB_MODE_PRESS, WALK_LOCATE_PressNeck, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_STOP_AT_MAX, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 5 },
  { BACK_SUB_MODE_PRESS, WALK_LOCATE_SHOULDER, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_STOP_AT_MIN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PROGRAM, AXIS_STRONGEST, _3D_SPEED_2, 5 },
  { BACK_SUB_MODE_PRESS, WALK_LOCATE_PressNeck, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_STOP_AT_MAX, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 5 },
  { BACK_SUB_MODE_PRESS, WALK_LOCATE_SHOULDER, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_STOP_AT_MIN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PROGRAM, AXIS_STRONGEST, _3D_SPEED_2, 5 },
  { BACK_SUB_MODE_PRESS, WALK_LOCATE_PressNeck, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_STOP_AT_MAX, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 5 },
  { BACK_SUB_MODE_PRESS, WALK_LOCATE_SHOULDER, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_RUN_STOP, 3, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_STOP_AT_MIN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
     //=========================================肩颈部揉捏-指手法1-指压=========================================--93
  { BACK_SUB_MODE_PRESS, WALK_SHOULDER_WAIST_2_10, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_KNEAD, WALK_LOCATE_SHOULDER, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_TOGGLE, 2, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_KNEAD, WALK_SHOULDER_WAIST_2_10, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_TOGGLE, 2, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_KNEAD, WALK_LOCATE_SHOULDER, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_FITFUL, 10, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
     //=========================================背上部-指压-揉捏-手法2-手法1=========================================--100
  { BACK_SUB_MODE_KNEAD, WALK_LOCATE_NeckMed, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_KNEAD, WALK_LOCATE_SHOULDER, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_FITFUL, 3, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
   { BACK_SUB_MODE_PRESS, WALK_DEC_PULSE, 10, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, 0, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_WAVELET, WALK_LOCATE_PARK, 0, KNEAD_RUBBING, 3, KNOCK_PWM, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_STOP_AT_MIN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_PRESS, WALK_LOCATE_NeckMed, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_PRESS, WALK_LOCATE_SHOULDER, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_PRESS, WALK_DEC_PULSE, 10, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, 0, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_WAVELET, WALK_LOCATE_PARK, 0, KNEAD_RUBBING, 3, KNOCK_PWM, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
     //=========================================肩颈部揉捏-手法1--指压-手法3=========================================--110
  { BACK_SUB_MODE_KNEAD, WALK_SHOULDER_WAIST_4_10, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_PRESS, WALK_SHOULDER_WAIST_5_10, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_KNEAD, WALK_SHOULDER_WAIST_2_10, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_FITFUL, 5, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_PRESS, WALK_SHOULDER_WAIST_1_10, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
  { BACK_SUB_MODE_PRESS, WALK_SHOULDER_WAIST_3_10, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 }
     //=========================================背上部揉捏-手法1-指压=========================================--116
};

//BACK_MAIN_MODE_MANUAL;
/*

             case H10_KEY_LOCATE_FULL:     nKeyBackLocate = LOCATE_FULL_BACK; break;//work
             case H10_KEY_LOCATE_PART:     nKeyBackLocate = LOCATE_PARTIAL; break;//work
             case H10_KEY_LOCATE_POINT:    nKeyBackLocate = LOCATE_POINT; break;//work



*/
const WALK_KNEAD_KNOCK_MOTOR_STRUCT_AUTO AutoFunction4_124[] = 
{	
  
 {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER ,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_5,0},
 
  
    //颈部来回揉捏		
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK    ,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_3,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_5,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK    ,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_5,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_4,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK    ,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_4,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_NeckMed ,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_5,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK    ,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_5,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_4,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK    ,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_4,_3D_SPEED_7,0},

  //上提   揉捏宽度：窄 窄 揉
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER ,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER ,0 ,KNEAD_STOP_AT_MIN,0,KNOCK_STOP ,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_NeckMed  ,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0}, 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_Ear      ,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP             ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},  
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_Ear      ,0,KNEAD_STOP_AT_MED  ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK    ,10,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,10},

  //上提   揉捏宽度：MED MED 揉
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER ,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER ,0 ,KNEAD_STOP_AT_MED,0,KNOCK_STOP ,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_NeckMed  ,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0}, 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_Ear      ,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP             ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},  
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_Ear      ,0,KNEAD_STOP_AT_MED  ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK    ,10,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,10},






//add 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0 ,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_NeckMed,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0}, 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_1_10,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_1_9,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},

 {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0}, 
 {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,2,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},



//end 


  //上提   揉捏宽度：窄 窄 揉

 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_5,0},
 
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP_AT_MIN         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_Ear,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,10,KNEAD_STOP             ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_Ear,0,KNEAD_STOP_AT_MED         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},


  //上提   揉捏宽度：MED MED 揉
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER ,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER ,0 ,KNEAD_STOP_AT_MED,0,KNOCK_STOP ,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_NeckMed  ,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0}, 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_Ear      ,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP             ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},  
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_Ear      ,0,KNEAD_STOP_AT_MED  ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK    ,10,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,10},




//  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,10,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,10},
 //add 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_5,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_5,0},
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0 ,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_NeckMed,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0}, 
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_1_10,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_1_9,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},

 {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0}, 
 //{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,2,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
 {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0}, 
 {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,2,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},


//end 
 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_5,0},
 
 {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0}, 
 {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,2,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},



//end 



  //上提   揉捏宽度：窄
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0 ,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_Ear,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_5,0}, 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_Ear,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
 //add 
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_NeckMed,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0}, 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_1_10,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_1_9,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},

 {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0}, 
 {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,2,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},

//end 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0}, 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_Ear,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0}, 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_Ear,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
 //add 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0 ,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_NeckMed,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0}, 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_1_10,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_1_9,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},

 {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0}, 
 {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MED,2,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},



//end 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0}, 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_Ear,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  
 //
 {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0}, 
 {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MED,3,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},

  // 第 3 节 MIN/////////////////////////////////////////////////////////
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10,0 ,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_2,_3D_SPEED_5,0},
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_2,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_5,_3D_PROGRAM,_3D_5,_3D_SPEED_5,0},  
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_2,_3D_PROGRAM,_3D_2,_3D_SPEED_2,0},

  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},  
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_5,_3D_PROGRAM,_3D_5,_3D_SPEED_5,0},  
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
 
 {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,5,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},//ADD

  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_4_10,0 ,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,_3D_2,_3D_SPEED_5,0},
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_2,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_5,_3D_PROGRAM,_3D_5,_3D_SPEED_5,0},  
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},

  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},  
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_5,_3D_SPEED_5,0},  
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_4,_3D_SPEED_4,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,5,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},

  // 第 3 节 MIN/////////////////////////////////////////////////////////
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10,0 ,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_2,_3D_SPEED_5,0},
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_5,_3D_PROGRAM,_3D_5,_3D_SPEED_5,0},  
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},

  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_2,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},  
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_5,_3D_PROGRAM,_3D_5,_3D_SPEED_5,0},  
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,5,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},

  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_4_10,0 ,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_2,_3D_SPEED_5,0},
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_2,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_5,_3D_PROGRAM,_3D_5,_3D_SPEED_5,0},  
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},

  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},  
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_5,_3D_PROGRAM,_3D_5,_3D_SPEED_5,0},  
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},





  
  //滑肩  肩部抚摸  揉捏宽度：中
   {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0 ,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER    ,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10,0,KNEAD_STOP ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER    ,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},



  //滑肩  肩部抚摸  揉捏宽度：窄
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0 ,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_5_10,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER    ,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_5_10,0,KNEAD_STOP ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER    ,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_5_10,0,KNEAD_STOP ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER    ,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_5_10,0,KNEAD_STOP ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER    ,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_5_10,0,KNEAD_STOP ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
 





  
  //滑肩  肩部抚摸  揉捏宽度：宽
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0 ,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_4_10,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER    ,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_4_10,0,KNEAD_STOP ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER    ,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_4_10,0,KNEAD_STOP ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER    ,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},

//MIN
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,1,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_3,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,1,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_3,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_1_10,0,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_3,0},
  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_1_10,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_3,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_3,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK       ,20,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_1_10,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_3,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_3,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK       ,20,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},

  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_3_10,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_3,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_4_10,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_3,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK       ,20,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_3_10,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_3,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_4_10,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_3,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK       ,20,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  
  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_5_10,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_3,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_6_10,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_3,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK       ,20,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_5_10,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_3,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_6_10,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_3,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK       ,20,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  
  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_8_10,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_3,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_9_10,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_3,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK       ,20,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_8_10,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_3,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_9_10,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_3,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK       ,20,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  
  //指压到顶
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_PressNeck,0,KNEAD_STOP           ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK     ,0,KNEAD_RUN_STOP_AT_MIN,1,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_7,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER ,0,KNEAD_STOP           ,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK     ,0,KNEAD_STOP           ,0,KNOCK_RUN,40,0,SPEED_4,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK     ,0,KNEAD_RUN_STOP_AT_MIN,3,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},
  

  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER ,0,KNEAD_STOP           ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK     ,20,KNEAD_RUN_STOP_AT_MAX,1,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_7,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP           ,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK     ,20,KNEAD_STOP           ,0,KNOCK_RUN,40,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK     ,0,KNEAD_RUN_STOP_AT_MAX,3,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},
 


//
  //颈部来回揉捏		
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK    ,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_3,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_5,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK    ,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_5,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_4,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK    ,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_4,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_NeckMed ,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_5,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK    ,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_5,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_4,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK    ,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_4,_3D_SPEED_7,0},
  

 {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,0,KNEAD_RUN         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
 {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,0,KNEAD_RUN         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
 


  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MAX,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MIN,0,KNOCK_RUN,0,0,SPEED_5,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,10},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MAX,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MIN,0,KNOCK_RUN,0,0,SPEED_5,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,10},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MAX,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MIN,0,KNOCK_RUN,0,0,SPEED_5,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,10},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MAX,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MIN,0,KNOCK_RUN,0,0,SPEED_5,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,10},

  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,2,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},



  //搓背  
  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_5,_3D_PROGRAM,_3D_4,_3D_SPEED_7,0},

  {BACK_SUB_MODE_RUBBING,WALK_SHOULDER_WAIST_6_10,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //WALK_SHOULDER_WAIST_5_10  WALK_LOCATE_SHOULDER
  {BACK_SUB_MODE_RUBBING,WALK_SHOULDER_WAIST_3_10,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},




  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_PressNeck,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},

  {BACK_SUB_MODE_RUBBING,WALK_SHOULDER_WAIST_6_10,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //WALK_SHOULDER_WAIST_5_10  WALK_LOCATE_SHOULDER
  {BACK_SUB_MODE_RUBBING,WALK_SHOULDER_WAIST_3_10,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},



  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_PressNeck,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},

  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_NeckMed,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},

  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_SHOULDER,0,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP_AT_MED,0,KNOCK_RUN_STOP,1,4,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_STOP,8,2,SPEED_4,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP_AT_MED,0,KNOCK_RUN_STOP,8,2,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_STOP,9,1,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},	
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},	
  //肩部捶打
  {BACK_SUB_MODE_KNEAD     ,WALK_LOCATE_PARK, 0,KNEAD_RUN_STOP_AT_MIN,5,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP       ,0,KNOCK_RUN_STOP,8,2,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MED,0,KNOCK_RUN_STOP,7,3,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_STOP,6,4,SPEED_4,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MED,0,KNOCK_RUN_STOP,5,5,SPEED_5,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},
  
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_STOP,6,4,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MED,0,KNOCK_RUN_STOP,6,4,SPEED_6,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_7,0},
  // 第 3 节 MIN/////////////////////////////////////////////////////////
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,5,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},

  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10,0 ,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_2,_3D_SPEED_5,0},
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_2,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},  
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},

  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},  
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},  
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,5,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},

  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_4_10,0 ,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,_3D_2,_3D_SPEED_5,0},
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_2,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},  
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},

  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},  
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},  
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},

  //捶击定位（窄中宽）
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,WAIST_POSITION+0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MIN,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MAX,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MIN,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MAX,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MIN,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_RUN_STOP_AT_MED,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_RUN_STOP_AT_MAX,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,WAIST_POSITION+0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,50,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //捶击定位（窄中宽）
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MIN,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MAX,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MIN,0,KNOCK_RUN,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MAX,0,KNOCK_RUN,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MIN,0,KNOCK_RUN,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MAX,0,KNOCK_RUN,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_RUN_STOP_AT_MIN,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_RUN_STOP_AT_MED,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_RUN_STOP_AT_MAX,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
/////////////

};

//BACK_MAIN_MODE_MANUAL;
/*

             case H10_KEY_LOCATE_FULL:     nKeyBackLocate = LOCATE_FULL_BACK; break;//work
             case H10_KEY_LOCATE_PART:     nKeyBackLocate = LOCATE_PARTIAL; break;//work
             case H10_KEY_LOCATE_POINT:    nKeyBackLocate = LOCATE_POINT; break;//work



*/
const WALK_KNEAD_KNOCK_MOTOR_STRUCT_AUTO AutoFunction4_old[] = 
{	
  
 {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER ,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_5,0},
 
  
    //颈部来回揉捏		
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK    ,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_3,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_5,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK    ,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_5,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_4,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK    ,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_4,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_NeckMed ,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_5,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK    ,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_5,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_4,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK    ,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_4,_3D_SPEED_7,0},

  //上提   揉捏宽度：窄 窄 揉
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER ,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER ,0 ,KNEAD_STOP_AT_MIN,0,KNOCK_STOP ,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_NeckMed  ,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0}, 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_Ear      ,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP             ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},  
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_Ear      ,0,KNEAD_STOP_AT_MED  ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK    ,10,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,10},

  //上提   揉捏宽度：MED MED 揉
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER ,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER ,0 ,KNEAD_STOP_AT_MED,0,KNOCK_STOP ,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_NeckMed  ,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0}, 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_Ear      ,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP             ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},  
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_Ear      ,0,KNEAD_STOP_AT_MED  ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK    ,10,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,10},






//add 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0 ,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_NeckMed,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0}, 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_1_10,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_1_9,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},

 {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0}, 
 {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,2,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},



//end 


  //上提   揉捏宽度：窄 窄 揉

 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_5,0},
 
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP_AT_MIN         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_Ear,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,10,KNEAD_STOP             ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_Ear,0,KNEAD_STOP_AT_MED         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},


  //上提   揉捏宽度：MED MED 揉
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER ,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER ,0 ,KNEAD_STOP_AT_MED,0,KNOCK_STOP ,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_NeckMed  ,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0}, 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_Ear      ,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP             ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},  
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_Ear      ,0,KNEAD_STOP_AT_MED  ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK    ,10,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,10},




//  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,10,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,10},
 //add 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_5,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_5,0},
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0 ,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_NeckMed,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0}, 
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_1_10,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_1_9,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},

 {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0}, 
 //{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,2,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
 {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0}, 
 {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,2,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},


//end 
 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_5,0},
 
 {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0}, 
 {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,2,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},



//end 



  //上提   揉捏宽度：窄
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0 ,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_Ear,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_5,0}, 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_Ear,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
 //add 
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_NeckMed,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0}, 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_1_10,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_1_9,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},

 {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0}, 
 {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,2,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},

//end 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0}, 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_Ear,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0}, 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_Ear,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
 //add 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0 ,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_NeckMed,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0}, 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_1_10,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_1_9,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},

 {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0}, 
 {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MED,2,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},



//end 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0}, 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_Ear,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  
 //
 {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0}, 
 {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MED,3,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},

  // 第 3 节 MIN/////////////////////////////////////////////////////////
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10,0 ,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_2,_3D_SPEED_5,0},
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_2,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_5,_3D_PROGRAM,_3D_5,_3D_SPEED_5,0},  
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_2,_3D_PROGRAM,_3D_2,_3D_SPEED_2,0},

  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},  
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_5,_3D_PROGRAM,_3D_5,_3D_SPEED_5,0},  
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
 
 {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,5,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},//ADD

  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_4_10,0 ,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,_3D_2,_3D_SPEED_5,0},
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_2,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_5,_3D_PROGRAM,_3D_5,_3D_SPEED_5,0},  
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},

  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},  
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_5,_3D_SPEED_5,0},  
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_4,_3D_SPEED_4,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,5,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},

  // 第 3 节 MIN/////////////////////////////////////////////////////////
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10,0 ,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_2,_3D_SPEED_5,0},
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_5,_3D_PROGRAM,_3D_5,_3D_SPEED_5,0},  
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},

  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_2,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},  
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_5,_3D_PROGRAM,_3D_5,_3D_SPEED_5,0},  
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,5,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},

  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_4_10,0 ,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_2,_3D_SPEED_5,0},
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_2,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_5,_3D_PROGRAM,_3D_5,_3D_SPEED_5,0},  
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},

  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},  
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_5,_3D_PROGRAM,_3D_5,_3D_SPEED_5,0},  
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},





  
  //滑肩  肩部抚摸  揉捏宽度：中
   {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0 ,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER    ,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10,0,KNEAD_STOP ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER    ,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},



  //滑肩  肩部抚摸  揉捏宽度：窄
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0 ,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_5_10,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER    ,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_5_10,0,KNEAD_STOP ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER    ,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_5_10,0,KNEAD_STOP ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER    ,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_5_10,0,KNEAD_STOP ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER    ,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_5_10,0,KNEAD_STOP ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
 





  
  //滑肩  肩部抚摸  揉捏宽度：宽
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0 ,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_4_10,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER    ,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_4_10,0,KNEAD_STOP ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER    ,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_4_10,0,KNEAD_STOP ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER    ,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},

//MIN
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,1,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_3,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,1,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_3,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_1_10,0,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_3,0},
  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_1_10,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_3,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_3,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK       ,20,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_1_10,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_3,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_3,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK       ,20,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},

  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_3_10,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_3,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_4_10,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_3,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK       ,20,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_3_10,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_3,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_4_10,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_3,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK       ,20,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  
  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_5_10,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_3,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_6_10,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_3,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK       ,20,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_5_10,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_3,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_6_10,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_3,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK       ,20,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  
  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_8_10,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_3,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_9_10,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_3,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK       ,20,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_8_10,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_3,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_9_10,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_3,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK       ,20,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  
  //指压到顶
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_PressNeck,0,KNEAD_STOP           ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK     ,0,KNEAD_RUN_STOP_AT_MIN,1,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_7,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER ,0,KNEAD_STOP           ,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK     ,0,KNEAD_STOP           ,0,KNOCK_RUN,40,0,SPEED_4,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK     ,0,KNEAD_RUN_STOP_AT_MIN,3,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},
  

  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER ,0,KNEAD_STOP           ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK     ,20,KNEAD_RUN_STOP_AT_MAX,1,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_7,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP           ,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK     ,20,KNEAD_STOP           ,0,KNOCK_RUN,40,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK     ,0,KNEAD_RUN_STOP_AT_MAX,3,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},
 


//
  //颈部来回揉捏		
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK    ,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_3,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_5,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK    ,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_5,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_4,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK    ,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_4,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_NeckMed ,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_5,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK    ,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_5,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_4,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK    ,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_4,_3D_SPEED_7,0},
  

 {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,0,KNEAD_RUN         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
 {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,0,KNEAD_RUN         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
 


  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MAX,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MIN,0,KNOCK_RUN,0,0,SPEED_5,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,10},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MAX,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MIN,0,KNOCK_RUN,0,0,SPEED_5,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,10},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MAX,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MIN,0,KNOCK_RUN,0,0,SPEED_5,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,10},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MAX,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MIN,0,KNOCK_RUN,0,0,SPEED_5,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,10},

  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,2,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},



  //搓背  
  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_5,_3D_PROGRAM,_3D_4,_3D_SPEED_7,0},

  {BACK_SUB_MODE_RUBBING,WALK_SHOULDER_WAIST_6_10,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //WALK_SHOULDER_WAIST_5_10  WALK_LOCATE_SHOULDER
  {BACK_SUB_MODE_RUBBING,WALK_SHOULDER_WAIST_3_10,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},




  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_PressNeck,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},

  {BACK_SUB_MODE_RUBBING,WALK_SHOULDER_WAIST_6_10,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //WALK_SHOULDER_WAIST_5_10  WALK_LOCATE_SHOULDER
  {BACK_SUB_MODE_RUBBING,WALK_SHOULDER_WAIST_3_10,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},



  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_PressNeck,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},

  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_NeckMed,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},

  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_SHOULDER,0,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP_AT_MED,0,KNOCK_RUN_STOP,1,4,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_STOP,8,2,SPEED_4,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP_AT_MED,0,KNOCK_RUN_STOP,8,2,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_STOP,9,1,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},	
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},	
  //肩部捶打
  {BACK_SUB_MODE_KNEAD     ,WALK_LOCATE_PARK, 0,KNEAD_RUN_STOP_AT_MIN,5,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP       ,0,KNOCK_RUN_STOP,8,2,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MED,0,KNOCK_RUN_STOP,7,3,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_STOP,6,4,SPEED_4,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MED,0,KNOCK_RUN_STOP,5,5,SPEED_5,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},
  
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_STOP,6,4,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MED,0,KNOCK_RUN_STOP,6,4,SPEED_6,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_7,0},
  // 第 3 节 MIN/////////////////////////////////////////////////////////
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,5,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},

  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10,0 ,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_2,_3D_SPEED_5,0},
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_2,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},  
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},

  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},  
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},  
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,5,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},

  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_4_10,0 ,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,_3D_2,_3D_SPEED_5,0},
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_2,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},  
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},

  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},  
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},  
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},

  //捶击定位（窄中宽）
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,WAIST_POSITION+0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_RUN_STOP_AT_MED,0,KNOCK_RUN_WIDTH,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_RUN_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,WAIST_POSITION+0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,50,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //捶击定位（窄中宽）
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_RUN_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_RUN_STOP_AT_MED,0,KNOCK_RUN_WIDTH,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_RUN_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
/////////////

};
